---
- name: Assert role variables
  ansible.builtin.import_tasks: assert.yml

- name: Install Redis server
  ansible.builtin.package:
    name: redis-server
    state: present

- name: Set redis bind
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: "^#?\\s*bind\\s"
    line: "bind {{ redis_bind }}"
  notify: Restart redis

- name: Set redis password
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: "^#?\\s?requirepass"
    line: "requirepass {{ redis_password }}"
  no_log: true
  notify: Restart redis

- name: Enable and start Redis service
  ansible.builtin.systemd:
    name: redis-server
    state: started
    enabled: true
