---
namespace: astappiev
name: common
description: Essential Linux roles for most common tasks.
version: 1.6.0

readme: README.md

authors:
  - astappiev

license:
  - MIT

tags:
  - system
  - security
  - administration
  - linux
  - infrastructure

dependencies:
  ansible.mysql: ">=5.1.0"
  ansible.posix: ">=2.0.0"
  ansible.utils: ">=6.0.0"
  community.general: ">=13.0.1"

repository: https://github.com/astappiev/ansible-collection-common
documentation: https://github.com/astappiev/ansible-collection-common
issues: https://github.com/astappiev/ansible-collection-common/issues

build_ignore: []
