---
- name: Uploading service file
  ansible.builtin.template:
    src: service.j2
    dest: "{{ systemd_base_path | default('/etc/systemd/system') }}/{{ systemd_timer_name }}.service"
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd
  become: true

- name: Uploading timer file
  ansible.builtin.template:
    src: timer.j2
    dest: "{{ systemd_base_path | default('/etc/systemd/system') }}/{{ systemd_timer_name }}.timer"
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd
  become: true

- name: Enabling timers
  ansible.builtin.systemd:
    name: "{{ systemd_timer_name }}.timer"
    state: started
    enabled: true
    masked: false
  become: true
  when: not ansible_check_mode
