---
_hostname_colors_map:
  black: '30'
  red: '31'
  green: '32'
  yellow: '33'
  blue: '34'
  magenta: '35'
  cyan: '36'
  white: '37'

hostname_prompt_color_code: "{{ _hostname_colors_map.get(hostname_prompt_color, '34') }}"
