---
- name: Remove NodeSource repository
  ansible.builtin.deb822_repository:
    name: nodesource
    state: absent
  register: nodejs_repo
  when: ansible_facts['os_family'] == 'Debian'

- name: Remove NodeSource repository
  ansible.builtin.yum_repository:
    name: nodesource
    state: absent
  register: nodejs_repo
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install Node.js from system repository
  ansible.builtin.package:
    name: nodejs
    update_cache: "{{ nodejs_repo is changed }}"
    state: present
