---
- name: Install Node.js from standard repository
  ansible.builtin.import_tasks: install-system.yml
  when: nodejs_install_source == 'distro'

- name: Install Node.js from NodeSource repository
  ansible.builtin.import_tasks: install-nodesource.yml
  when: nodejs_install_source == 'nodesource'

- name: Enable specified package managers via Corepack
  ansible.builtin.command:
    cmd: corepack enable "{{ item }}"
    creates: "/usr/local/bin/{{ item }}"
  loop: "{{ nodejs_corepack_enable }}"
  when:
    - nodejs_corepack_enable | length > 0

- name: Ensure npm global packages are installed
  community.general.npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    global: true
  loop: "{{ nodejs_npm_global_packages }}"
  when: nodejs_npm_global_packages | length > 0
