- name: Configure bash aliases for {{ user.name }}
  ansible.builtin.blockinfile:
    path: "~/.bashrc"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} ANSIBLE MANAGED ALIASES"
    block: |
      export LS_OPTIONS='--color=auto'
      test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
      alias ls='ls $LS_OPTIONS'
      alias ll='ls $LS_OPTIONS -l'
      alias l='ls $LS_OPTIONS -lA'

      alias dir='dir --color=auto'
      alias vdir='vdir --color=auto'
      alias grep='grep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias egrep='egrep --color=auto'

      alias ..='cd ..'
      alias ...='cd ../..'

      alias rm='rm -i'
      alias cp='cp -i'
      alias mv='mv -i'

- name: Update ssh client config for {{ user.name }}
  ansible.builtin.copy:
    dest: "~/.ssh/config"
    content: |
      Host *
          StrictHostKeyChecking accept-new
          ServerAliveInterval 60
          ServerAliveCountMax 3
    mode: '600'
