---
# The hostname to set. By default whatever the inventory is set to.
hostname: "{{ inventory_hostname_short }}"  # noqa: var-naming[no-role-prefix]

# Should the machine be rebooted when the hostname is changed?
hostname_reboot: true
