---
- name: Install timezone information
  ansible.builtin.package:
    name: "{{ timezone_packages }}"
    state: present

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
