---
- name: Validate docker_install_source
  ansible.builtin.assert:
    that:
      - docker_install_source is defined
      - docker_install_source in ["distro", "docker-ce"]
    fail_msg: "docker_install_source must be either 'docker-ce' or 'distro', got '{{ docker_install_source }}'"
    quiet: true

- name: Validate docker_users
  ansible.builtin.assert:
    that:
      - docker_users is defined
      - docker_users is iterable
    fail_msg: "docker_users must be a list"
    quiet: true

- name: Validate docker_simple_cli
  ansible.builtin.assert:
    that:
      - docker_simple_cli is defined
      - docker_simple_cli is boolean
    fail_msg: "docker_simple_cli must be a boolean value"
    quiet: true
