---
- name: Remove old/conflicting Docker packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - docker-buildx
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: true

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    uris: https://download.docker.com/linux/debian
    types: deb
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: https://download.docker.com/linux/debian/gpg
    install_python_debian: true
    state: present
  notify: Apt update

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
