---
- name: Remove old/conflicting Docker packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - docker-buildx
      - docker-cli
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: true

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"
    types: deb
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    install_python_debian: true
    state: present
  register: _docker_repo_result

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: "{{ _docker_repo_result is changed }}"
    state: present
