---
- name: Validate variables
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install Docker from system packages
  ansible.builtin.import_tasks: install-system.yml
  when: docker_install_source == "distro"

- name: Install Docker from docker.com repository
  ansible.builtin.import_tasks: install-docker-ce.yml
  when: docker_install_source == "docker-ce"

- name: Ensure Docker service is enabled and started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: not docker_rootless and not ansible_check_mode

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  when:
    - docker_users | length > 0
    - not docker_rootless

- name: Enable IPv6 forwarding (sysctl)
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    sysctl_set: true
    reload: true
  when: docker_ipv6

- name: Configure ipv6 for Docker
  ansible.builtin.import_tasks: ipv6.yml
  when: docker_ipv6 and not docker_rootless

- name: Install rootless Docker prerequisites
  ansible.builtin.import_tasks: rootless-prerequisites.yml
  when: docker_rootless

- name: Configure rootless Docker
  ansible.builtin.import_tasks: rootless.yml
  when: docker_rootless

- name: Install simple Docker CLI
  ansible.builtin.import_tasks: simple.yml
  when: docker_simple_cli

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
