---
- name: Configure Docker environment
  ansible.builtin.blockinfile:
    path: "{{ user_home }}/.bashrc"
    block: |
      export PATH=/usr/share/docker.io/contrib:$PATH
      export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Docker rootless"
    create: true
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0600"

- name: Install rootless Docker
  ansible.builtin.shell: >
    export XDG_RUNTIME_DIR=/run/user/$(id -u) &&
    export PATH=/usr/share/docker.io/contrib:$PATH &&
    dockerd-rootless-setuptool.sh install
  args:
    creates: "{{ user_home }}/.config/systemd/user/docker.service"

- name: Create systemd user directory for Docker
  ansible.builtin.file:
    path: "{{ user_home }}/.config/systemd/user/docker.service.d"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0700"

- name: Configure rootless Docker service
  ansible.builtin.copy:
    content: |
      # Ansible managed

      [Service]
      {% if docker_rootless_network_driver == "pasta" %}
      Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_NET=pasta"
      Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=implicit"
      {% elif docker_rootless_network_driver == "slirp4netns" %}
      Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
      {% endif %}

      {% if docker_ipv6 %}
      Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS=--ipv6"
      {% endif %}
    dest: "{{ user_home }}/.config/systemd/user/docker.service.d/override.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0600"
  notify:
    - User daemon reload
    - User docker restart

- name: Ensure Docker config dir exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config/docker"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  when: docker_ipv6

- name: Configure Docker daemon (daemon.json)
  ansible.builtin.copy:
    dest: "{{ user_home }}/.config/docker/daemon.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
    content: |
      {
        "ipv6": true,
        "fixed-cidr-v6": "{{ docker_ipv6_default_subnet | ansible.utils.ipsubnet(docker_ipv6_rootless_subnet_size, ansible_loop.index0) }}"
      }
  when: docker_ipv6
  notify: User docker restart
