---
- name: Install rootless Docker prerequisites
  ansible.builtin.apt:
    name:
      - uidmap
      - dbus-user-session
    state: present

- name: Disable root Docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - docker.service
    - docker.socket
  when: not ansible_check_mode

- name: Remove root Docker socket
  ansible.builtin.file:
    path: /var/run/docker.sock
    state: absent

- name: Install pasta for rootless Docker networking
  ansible.builtin.apt:
    name: passt
    state: present
  when: docker_rootless_network_driver == "pasta"

- name: Install slirp4netns for rootless Docker networking
  ansible.builtin.apt:
    name: slirp4netns
    state: present
  when: docker_rootless_network_driver == "slirp4netns"

- name: Install rootless Docker dependencies
  ansible.builtin.apt:
    name: docker-ce-rootless-extras
    state: present
  when: docker_install_source == 'docker-ce'

- name: Install rootless Docker dependencies
  ansible.builtin.apt:
    name: rootlesskit
    state: present
  when: docker_install_source == 'distro'

- name: Create symbolic link for docker binary
  ansible.builtin.file:
    src: /usr/bin/docker
    dest: /usr/share/docker.io/contrib/docker
    state: link
    force: true
  when: docker_install_source == 'distro'

- name: Configure unprivileged port start
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "{{ docker_unprivileged_port_start }}"
    state: present
    sysctl_set: true
    reload: true
  when: docker_unprivileged_port_start is defined and docker_unprivileged_port_start > 0
